# Many thanks to https://petercoding.com/flutter/2021/07/18/using-github-actions-with-flutter/

name: CI-QA

on:
  push:
    branches: [develop]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    name: QA Pipeline
    runs-on: ubuntu-latest
    env:
      JAVA_VERSION: "11.0"
      FLUTTER_VERSION: "3.0.5"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: $
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: $
      - run: flutter format -l 1000 --output none --set-exit-if-changed  lib/ test/
      - run: flutter pub run build_runner build --no-track-performance --delete-conflicting-outputs
      - run: flutter pub get --suppress-analytics --verbose
      - run: flutter analyze --no-pub --no-congratulate
      - run: flutter test --no-pub --null-assertions --coverage